### ISSUE TITLE
if email gets canceled at filter:email.cancel nodebb/email-helper/any-email not loading

### ISSUE THREAD

**Issue by cisnerosebastian** [julianlam/nodebb-plugin-email-helper#96]
I understand why this is hapening, I'm just wondering if there should be a way to get this fixed. Let me explain.

email-helper plugin is for testing, developing, right?

In my current project, I need to CANCEL some emails at filter:email.cancel hook if certain condition meets. I still want to be able to test the emails at the nodebb/email-helper/any-email url, but can't, because the email gets canceled before reaching to the static:email.send hook that this plugin uses. 

I was wondering if this plugin can add an extra parameter maybe in the filter:email.prepare hook, that reaches the filter:email.cancel hook indicating that this call is just from the email-helper plugin so we can NOT Cancel the email if the call cames from the email-helper plugin.

**Comment by julianlam** [comment]
> email-helper plugin is for testing, developing, right?

Yeah. Oh my god I can't believe someone is actually using this for testing. That makes me feel happy haha.

I'll take a look and see if I can come up with something...

**Comment by julianlam** [comment]
I gave it some thought, and I don't know if I can actually do it through code. The whole idea behind the email-helper is to make it go through the code as closely as possible as though it were a real email. It tries not to interfere with other emailers too, so if you managed to skip the cancellation, then if you had another emailer, the email would get sent out, and they might not be desirable.

If you've managed to get it working via envvars, then that's probably the best solution for now.

I'll keep this in mind, though... not quite sure how to approach it though.
